---
title: "proyecto2"
output: word_document
date: "2025-02-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

install.packages("readxl")
library('readxl')
install.packages('dplyr')
library(dplyr)

library(dplyr)
install.packages('sf')
library(sf)
```

```{r datos, echo=TRUE}
# Leer un archivo Excel (.xlsx o .xls)
datos <- read_excel("propiedades_valencia.xlsx")
# Ver las primeras filas
View(datos)

load('Valencia_Sale.rda')

Valencia_Sale <- as.data.frame(st_drop_geometry(Valencia_Sale)) # creamos el dataframe
duplicados <- Valencia_Sale %>% group_by(ASSETID) %>% filter(n() > 1) %>% ungroup() # guardamos los duplicados
duplicados_buenos = duplicados %>% group_by(ASSETID) %>% filter(PRICE == min(PRICE)) %>% slice_head(n = 1) %>% ungroup() # de los duplicados, nos quedamos los de menor precio
Valencia_Sale <- anti_join(Valencia_Sale, duplicados, by = c("ASSETID", "PRICE")) # eliminamos los duplicados de la base de datos
Valencia_Sale <- rbind(Valencia_Sale, duplicados_buenos) # añadimos los duplicados buenos que nos queremos quedar

View(Valencia_Sale)
                  
```

```{r }
summary(Valencia_Sale)
duplicados = Valencia_Sale[duplicated(Valencia_Sale$ASSETID) | duplicated(Valencia_Sale$ASSETID, fromLast = TRUE), ]

View(duplicados)
```