---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
Setup
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
Carga de librerías
```{r }
library(dplyr)
library(readxl)
library(leaflet)
library(shiny)
library(dplyr)
library(readxl)
library(jsonlite)
library(stringr)
```

Carga de los datos
```{r }
datos = read_excel("C:/Users/rtorr/OneDrive/Documentos/uni/4º/Proyecto II/propiedades_valencia_2025.xlsx")
head(datos)
```
Limpieza y exploración

Eliminar duplicados
```{r}
nrow(datos)
duplicados <- datos %>% group_by(propertyCode) %>% filter(n() > 1) %>% ungroup()
nrow(duplicados)
duplicados_buenos = duplicados %>% group_by(propertyCode) %>%  slice_head(n = 1) %>% ungroup() # de los duplicados, nos quedamos los de menor precio
nrow(duplicados_buenos)
datos <- anti_join(datos, duplicados_buenos, by = c("propertyCode", "price")) # eliminamos los duplicados de la base de datos
datos <- rbind(datos, duplicados_buenos)
nrow(datos)
```
Arreglo de las variables en formato JSON

```{r}
head(datos$priceInfo)
datos <- datos %>% 
    mutate(
        priceInfo_clean = str_replace_all(priceInfo, "'", "\""), parsed_json = lapply(priceInfo_clean, function(x) tryCatch(fromJSON(x), error = function(e) NULL))) %>%
        rowwise() %>% 
        mutate(
            amount = parsed_json$price$amount %||% NA,
            currency = parsed_json$price$currencySuffix %||% NA, 
            former_price = parsed_json$price$priceDropInfo$formerPrice %||% NA, 
            price_drop_value = parsed_json$price$priceDropInfo$priceDropValue %||% NA, 
            price_drop_percentage = parsed_json$price$priceDropInfo$priceDropPercentage %||% NA) %>% 
            select(-parsed_json, -priceInfo_clean, -priceInfo)
```
```{r}
table(datos$detailedType) #Se puede ver que es una variable categórica
```

```{r}
head(table(datos$suggestedTexts)) #Tipo texto
```

```{r}
table(datos$highlight, useNA = "ifany") #categorical
datos <- datos %>%
    mutate(highlight = case_when(
        highlight == "{'groupDescription': 'Destacado'}" ~ "Destacado",
        highlight == "{'groupDescription': 'Top'}" ~ "Top",
        highlight == "{'groupDescription': 'Top+'}" ~ "Top+",
        highlight == "TRUE" ~ "True",
        highlight == "FALSE" ~ "False",
        TRUE ~ NA_character_
    ))
table(datos$highlight, useNA = "ifany")
```

```{r}
head(datos$parkingSpace)
datos <- datos %>%
    mutate(
        parkingSpace_clean = str_replace_all(parkingSpace, "'", "\""),
        parsed_parkingSpace = lapply(parkingSpace_clean, function(x) tryCatch(fromJSON(x), error = function(e) NULL))
    ) %>%
    rowwise() %>%
    mutate(
        hasParkingSpace = parsed_parkingSpace$hasParkingSpace %||% NA,
        isParkingSpaceIncludedInPrice = parsed_parkingSpace$isParkingSpaceIncludedInPrice %||% NA,
        parkingSpacePrice = parsed_parkingSpace$parkingSpacePrice %||% NA
    ) %>%
    ungroup() %>%
    select(-parsed_parkingSpace, -parkingSpace_clean, -parkingSpace)
```
```{r }
descProp = data.frame("variable" = colnames(datos),
                      "tipo" = c("id", "url", "text", rep("numerical", 3), rep("categorical", 2), "numerical", "binary", rep("numerical", 2), "text", rep("categorical", 5), rep("numerical", 2), "binary", "url", "numerical", "text", "binary", "categorical", rep("binary", 2), rep("numerical", 2), "categorical", "text", rep("binary", 4), rep("categorical", 3), rep("binary", 2), "binary", "numerical", "categorical", rep("numerical", 3), rep("binary", 2), "numerical"), stringsAsFactors = FALSE)
rownames(descProp) = descProp$variable
descProp
```

```{r }
datos2 = datos[,setdiff(colnames(datos), c("propertyCode", "thumbnail", "externalReference", "address", "url", "description", "suggestedTexts"))]
descProp = descProp[colnames(datos2),]
table(descProp$tipo)
```

```{r }
summary(datos2[,descProp$variable[descProp$tipo == "numerical"]])
```

Arreglo de la varialbe floor
```{r} 
table(datos2$floor)
datos2 <- datos2 %>% filter(is.na(floor) | floor != "st")
datos2[!is.na(datos2$floor) & datos2$floor == "ss", "floor"] <- "-0.5"
datos2[!is.na(datos2$floor) & datos2$floor == "bj", "floor"] <- "0"
datos2[!is.na(datos2$floor) & datos2$floor == "en", "floor"] <- "0.5"
datos2[!is.na(datos2$floor) & datos2$floor == "-2", "floor"] <- "2"
datos2$floor <- as.numeric(datos2$floor)
summary(datos2$floor)
```
Arreglo de la variable change

```{r}
datos2[datos2$change == "{}", "change"] <- NA
datos2$change <- as.numeric(datos2$change)
summary(datos2$change)
```

```{r }
mySD = apply(datos2[,descProp$variable[descProp$tipo == "numerical"]], 2, sd, na.rm = TRUE)
# Mejor calcular el coeficiente de variación porque no depende de las unidades o magnitud de las variables
myMU = colMeans(datos2[,descProp$variable[descProp$tipo == "numerical"]], na.rm = TRUE)
myCV = mySD/myMU
sort(myCV)
```

```{r }
apply(datos2[,descProp$variable[descProp$tipo == "binary"]], 2, table, useNA = "i")
apply(datos2[,descProp$variable[descProp$tipo == "binary"]], 2,
      function (x) round(100*table(x)/sum(table(x)), 2))
```

```{r }
apply(datos2[,descProp$variable[descProp$tipo == "categorical"]], 2, table, useNA = "i")
apply(datos2[,descProp$variable[descProp$tipo == "categorical"]], 2,
      function (x) round(100*table(x)/sum(table(x)), 2))
```

Eliminación de variables

```{r}
datos2 = datos2[,setdiff(colnames(datos2), c(""))]
descProp = descProp[colnames(datos2),]
```

```{r }
grandes <- datos %>% 
  filter(size > 500) %>% 
  arrange(desc(size)) %>% 
  slice_head(n = 5)
grandes_property_code_1 <- grandes$propertyCode[1]
grandes_property_code_2 <- grandes$propertyCode[2]
datos <- datos %>% filter(propertyCode != grandes_property_code_1)
datos <- datos %>% filter(propertyCode != grandes_property_code_2)
```
```{r }
ui <- fluidPage(
  titlePanel("Mapa Interactivo de Propiedades en Valencia"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("priceRange", "Rango de Precio:",
                  min = min(datos$price, na.rm = TRUE),
                  max = max(datos$price, na.rm = TRUE),
                  value = c(min(datos$price, na.rm = TRUE), max(datos$price, na.rm = TRUE)))
    ),
    mainPanel(
      leafletOutput("map")
    )
  )
)

server <- function(input, output, session) {
  filteredData <- reactive({
    datos %>% filter(price >= input$priceRange[1] & price <= input$priceRange[2])
  })

  output$map <- renderLeaflet({
    leaflet(filteredData()) %>%
      addTiles() %>%
      addCircleMarkers(
        ~longitude, ~latitude, 
        popup = ~paste(
          "Precio:", price, "<br>",
          "Ubicación:", ifelse(!is.na(neighborhood), neighborhood, municipality), "<br>",
          "URL:", sprintf('<a href="%s" target="_blank">Ver Propiedad</a>', url)
        ),
        clusterOptions = markerClusterOptions()  # Agrupar puntos cercanos
      )
  })
}

shinyApp(ui, server)
```
